routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */
 \URL::forceRootUrl(env('APP_URL'));
 Route::get('/', 'HomeController@index');
 Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
 Route::get('/quick-search', 'PagesController@quickSearch')->name('quick-search');
 Route::get('/noauth', 'HomeController@noauth')->name('noauth');

 Route::middleware('web')->group(function() {
    Route::middleware('guest')->namespace('Auth')->group(function() {
     Route::get('/', 'LoginController@showLoginForm')->name('login.main');
     Route::get('/attribute', 'LoginController@attribute')->name('login.attribute');
    	Route::get('login', 'LoginController@showLoginForm')->name('login.show-form');
    	Route::post('login', 'LoginController@login')->name('login');
    });
   Route::get('logout', 'Auth\LoginController@logout')->name('logout');
 });

 Route::middleware('web')->group(function() {
   Route::prefix('management')->namespace('Management')->as('management.')->group(function() {
       Route::prefix('user')->as('user.')->group(function() {
           Route::post('data', 'UserController@getData')->name('data');
           Route::delete('{id}', 'UserController@destroy')->name('show');
           Route::get('{id}', 'UserController@edit')->name('show');
           Route::get('{id}/change-password', 'UserController@changeOtherPassword')->name('other.change-password');
           Route::put('{id}/update-password', 'UserController@updateOtherPassword')->name('other.update-password');
       });
       Route::resource('user', 'UserController', ['except' => ['create', 'show']]);


       Route::get('login-history', 'UserHistoryController@showLoginHistory')->name('login-history');
       Route::post('login-history/data', 'UserHistoryController@getLoginHistoryData')->name('login-history.data');

       Route::prefix('role')->as('role.')->group(function() {
           Route::post('data', 'RoleController@getData')->name('data');
           Route::get('{id}', 'RoleController@show')->name('show');
           Route::get('auth/{id}', 'RoleController@show_auth')->name('show.auth');
           Route::post('{id}/{col}/{val}', 'RoleController@update_auth')->name('update.auth');
       });
       Route::resource('role', 'RoleController', ['except' => ['create', 'show']]);

       Route::prefix('menu')->as('menu.')->group(function() {
           Route::post('data', 'MenuController@getData')->name('data');
           Route::get('{id}', 'MenuController@show')->name('show');
       });
       Route::resource('menu', 'MenuController', ['except' => ['create', 'show']]);
   });
 });

Route::prefix('telnet')->namespace('Telnet')->as('telnet.')->group(function() {
    Route::prefix('olt-config')->as('olt-config.')->group(function() {
        Route::get('/clientstools/{id}/{config}/{setting}', 'OltConfigController@clientstools')->name('clientstools');
        Route::get('/autofindall', 'OltConfigController@autoFindAll')->name('autofindall');
        Route::get('/autofindhost/{host}', 'OltConfigController@autoFindHost')->name('autofindhost');
        Route::get('/checkpower/{host}/{sn}', 'OltConfigController@checkPowerSn')->name('checkpower');
        Route::get('/checkconfig/{id}/{config}', 'OltConfigController@checkConfig')->name('check-config');
    });

    Route::prefix('olt-clients')->as('olt-clients.')->group(function() {
        Route::post('/activation/{id}/{setting}/{config}', 'OltConfigController@activation')->name('activation');
        Route::post('/modify-sn/{id}/{sn}/{config}', 'OltConfigController@modifysn')->name('modify-sn');
        Route::post('/modify-traffic/{id}/{old}/{new}', 'OltConfigController@modifytraffic')->name('modify-traffic');
        Route::get('/activation/{id}/{setting}/{config}', 'OltConfigController@activation')->name('activation');
        Route::get('/modify-sn/{id}/{sn}/{config}', 'OltConfigController@modifysn')->name('modify-sn');
        Route::get('/modify-traffic/{id}/{new}/{config}', 'OltConfigController@modifytraffic')->name('modify-traffic');
    });
});


Route::prefix('olt')->namespace('Olt')->as('olt.')->group(function() {
    Route::prefix('ont')->as('ont.')->group(function() {
        Route::post('data', 'OntController@getData')->name('data');
        Route::get('/{id}', 'OntController@show')->name('show');
    });
    Route::resource('ont', 'OntController', ['except' => ['create', 'show']]);

    Route::prefix('host')->as('host.')->group(function() {
        Route::post('data', 'HostController@getData')->name('data');
        Route::get('/{id}', 'HostController@show')->name('show');
        Route::get('show-config/{id}', 'HostController@show_config')->name('show-config');
    });
    Route::resource('host', 'HostController', ['except' => ['create', 'show']]);

    Route::prefix('signal-formula')->as('signal-formula.')->group(function() {
        Route::post('data', 'SignalFormulaController@getData')->name('data');
        Route::get('/{id}', 'SignalFormulaController@show')->name('show');
    });
    Route::resource('signal-formula', 'SignalFormulaController', ['except' => ['create', 'show']]);

    Route::prefix('brand')->as('brand.')->group(function() {
        Route::post('data', 'BrandController@getData')->name('data');
        Route::get('/{id}', 'BrandController@show')->name('show');
    });
    Route::resource('brand', 'BrandController', ['except' => ['create', 'show']]);

    Route::prefix('clients')->as('clients.')->group(function() {
        Route::post('data', 'ClientsController@getData')->name('data');
        Route::get('data', 'ClientsController@getData')->name('data');
        Route::get('show-header/{id}', 'ClientsController@show_header')->name('show-header');
        Route::get('/{id}', 'ClientsController@show')->name('show');
        Route::get('/{form}/page', 'ClientsController@page')->name('page');
    });
    Route::resource('clients', 'ClientsController', ['except' => ['create', 'show']]);

    Route::prefix('clients-history')->as('clients-history.')->group(function() {
        Route::post('data', 'ClientsHistoryController@getData')->name('data');
        Route::get('/{id}', 'ClientsHistoryController@show')->name('show');
        Route::get('show-header/{id}', 'ClientsHistoryController@show_header')->name('show-header');
    });
    Route::resource('clients-history', 'ClientsHistoryController', ['except' => ['create', 'show']]);

    Route::prefix('isp')->as('isp.')->group(function() {
        Route::post('data', 'IspController@getData')->name('data');
        Route::get('/{id}', 'IspController@show')->name('show');
    });
    Route::resource('isp', 'IspController', ['except' => ['create', 'show']]);

    Route::prefix('customer')->as('customer.')->group(function() {
        Route::post('data', 'CustomerController@getData')->name('data');
        Route::get('regist/{id}', 'CustomerController@regist')->name('regist');
        Route::get('/{id}', 'CustomerController@show')->name('show');
        Route::get('/{form}/page', 'CustomerController@page')->name('page');

    });
    Route::resource('customer', 'CustomerController', ['except' => ['create', 'show']]);

    Route::prefix('customer-registration')->as('customer-registration.')->group(function() {
        Route::post('data', 'CustomerRegistrationController@getData')->name('data');
        Route::get('/{id}', 'CustomerRegistrationController@show')->name('show');
    });
    Route::resource('customer-registration', 'CustomerRegistrationController', ['except' => ['create', 'show']]);

    Route::prefix('customer-site')->as('customer-site.')->group(function() {
        Route::post('data', 'CustomerSiteController@getData')->name('data');
        Route::get('/{id}', 'CustomerSiteController@show')->name('show');
    });
    Route::resource('customer-site', 'CustomerSiteController', ['except' => ['create', 'show']]);

    Route::prefix('customer-switch')->as('customer-switch.')->group(function() {
        Route::post('data', 'CustomerSwitchController@getData')->name('data');
        Route::get('/{id}', 'CustomerSwitchController@show')->name('show');
        Route::get('/{form}/page', 'CustomerSwitchController@page')->name('page');

    });
    Route::resource('customer-switch', 'CustomerSwitchController', ['except' => ['create', 'show']]);

    Route::prefix('template')->as('template.')->group(function() {
        Route::post('data', 'TemplateController@getData')->name('data');
        Route::get('/{id}', 'TemplateController@show')->name('show');
        Route::get('/{form}/page', 'TemplateController@page')->name('page');
        Route::get('show-header/{id}', 'TemplateController@show_header')->name('show-header');


    });
    Route::resource('template', 'TemplateController', ['except' => ['create', 'show']]);

});

Route::prefix('monitoring')->namespace('Monitoring')->as('monitoring.')->group(function() {
    Route::resource('fiber-optic', 'FiberOpticController', ['except' => ['create', 'show']]);
    Route::resource('wireless', 'WirelessController', ['except' => ['create', 'show']]);
    Route::resource('bts', 'BtsController', ['except' => ['create', 'show']]);
    Route::resource('graphic', 'GraphicController', ['except' => ['create', 'show']]);
    Route::resource('network-map', 'NetworkMapController', ['except' => ['create', 'show']]);
    Route::resource('server-farm', 'ServerFarmController', ['except' => ['create', 'show']]);
    Route::resource('core-network', 'CoreNetworkController', ['except' => ['create', 'show']]);
});

Route::prefix('asset-management')->namespace('Asset')->as('asset.')->group(function() {

app/Http/Controllers/Olt/BrandController.php
<?php
namespace App\Http\Controllers\Olt;

use DataTables;
use Illuminate\Http\Request;
use App\Services\Olt\Brand;
use App\Http\Controllers\Controller;

class BrandController extends Controller
{

    public function index()
    {
        if(!getAuthMenu('olt.brand.index',VIEW)){
          return redirect()->route('noauth');
        }

        return view('olt.brand.index');
    }

    public function store(Request $request)
    {
        if(!getAuthMenu('olt.brand.index',CREATE)){
          return redirect()->route('noauth');
        }

        $this->validate($request, [
            'Name' => 'nullable|max:250',
            'Model' => 'nullable|max:250',
            'Type' => 'nullable|max:250',
            'Version' => 'nullable|max:250',
            'Remark' => 'nullable|max:250'
        ]);

        $device = (new Brand())->post($request->all());

        return redirect()->route('olt.brand.index')->with('notif_success', 'New Brand has been added successfully!');
    }

    public function show($id)
    {

        $device = (new Brand())->show($id)->data;

        return makeResponse(200, 'success', null, $device);
    }

    public function update($id, Request $request)
    {
        if(!getAuthMenu('olt.brand.index',UPDATE)){
          return redirect()->route('noauth');
        }

        $this->validate($request, [
            'Name' => 'nullable|max:250',
            'Model' => 'nullable|max:250',
            'Type' => 'nullable|max:250',
            'Version' => 'nullable|max:250',
            'Remark' => 'nullable|max:250'
        ]);

        $device = (new Brand())->put($id, $request->all());

        return redirect()->route('olt.brand.index')->with('notif_success', 'Brand has been update successfully!');
    }

    public function destroy($id)
    {
        if(!getAuthMenu('olt.brand.index',DELETE)){
          return redirect()->route('noauth');
        }

        $device = (new Brand())->delete($id);

        return redirect()->back()->with('notif_success', 'Brand has been deleted!');
    }

    public function getData(Request $request)
    {
        $results = (new Brand())->getAll($request);
        $paging = paginator($results);
        $list = array();
        $no = intval($request->start);
        foreach ($results->data as $datas) {
            $no++;
            $row = array();
            $datas->DT_RowIndex = $no;
            $list[] = $datas;
        }
        return response()->json([
            "draw" => intval($request->draw),
            "recordsTotal"    => intval($paging->total_records),
            "recordsFiltered" => intval($paging->total_records),
            "data" => $list
        ]);
    }
}

app/Http/Controllers/Olt/ClientsHistoryController.php
<?php
namespace App\Http\Controllers\Olt;

use DataTables;
use Illuminate\Http\Request;
use App\Services\Olt\Clients;
use App\Services\Olt\ClientsVlanService;
use App\Services\Olt\Isp;
use App\Services\Olt\Host;
use App\Services\Olt\Ont;
use App\Services\Olt\Customer;
use App\Services\Olt\Template;
use App\Services\Olt\LineProfile;
use App\Services\Olt\SrvProfile;
use App\Services\Olt\TrafficTable;
use App\Services\Olt\ClientsHistory;
use App\Services\Telnet\Olt;
use App\Services\Olt\ClientsTools;
use App\Http\Controllers\Controller;

class ClientsHistoryController extends Controller
{

    public function index()
    {
        if(!getAuthMenu('olt.clients-history.index',VIEW)){
          return redirect()->route('noauth');
        }

        $ont_list = (new Ont())->getAllActive(Null,Null);
        $datas['ont_list'] = (isset($ont_list->data)) ? $ont_list->data : null;
        return view('olt.clients-history.index',$datas);
    }

    public function store(Request $request)
    {
        if(!getAuthMenu('olt.clients-history.index',CREATE)){
          return redirect()->route('noauth');
        }

        $this->validate($request, [
            'IspCode' => 'nullable|max:250',
            'HostCode' => 'nullable|max:250',
            'CustomerCode' => 'nullable|max:250',
            'TemplateCode' => 'nullable|max:250',
            'VlanDownLink' => 'nullable|max:250',
            'FrameId' => 'nullable|max:250',
            'SlotId' => 'nullable|max:250',
            'PortId' => 'nullable|max:250',
            'OntVersion' => 'nullable|max:250',
            'OntSoftware' => 'nullable|max:250',
            'OntSn' => 'nullable|max:250',
            'ManagementMode' => 'nullable|max:250',
            'OntLineProfileId' => 'nullable|max:250',
            'OntSrvProfileId' => 'nullable|max:250',
            'VlanId'=> 'nullable|max:250',
            'VlanFrameId' => 'nullable|max:250',
            'VlanSlotId' => 'nullable|max:250',
            'VlanPortId' => 'nullable|max:250',
            'BoardID' => 'nullable|max:250',
            'TrafficTableId' => 'nullable|max:250',
            'NativeVlanEth1' => 'nullable|max:250',
            'NativeVlanEth2' => 'nullable|max:250',
            'NativeVlanEth3' => 'nullable|max:250',
            'NativeVlanEth4' => 'nullable|max:250'
        ]);

        $clients = (new Clients())->post($request->all());

        return redirect()->route('olt.clients-history.index')->with('notif_success', 'New Clients has been added successfully!');
    }

    public function show($id)
    {
        $results["clients"] = (new Clients())->show($id)->data;
        $results["host"] = (new Host)->show($results['clients']->HostCode)->data;
        $results["list_clientstools"] = (new ClientsTools)->show($id)->data;
        $results["clients_vlan_service"] = (new ClientsVlanService())->getAllActive($results["clients"]->CustomerCode)->data;

        return makeResponse(200, 'success', null, $results);
    }

    public function getData(Request $request)
    {
        $results = (new clients())->getAll($request)->data;
        // dd($results);

        return DataTables::of($results)
                          ->addIndexColumn()
                          ->addColumn('active', function ($clients) {
                                return '<i class="la la-close icon-lg text-danger"></i>';
                          })
                          ->rawColumns(['active'])
                          ->make(true);
    }
}

resources/views/olt/template/index.blade.php
@extends('layout.default') @section('content')
<div class="subheader py-2 {{ Metronic::printClasses('subheader', false) }}" id="kt_subheader">
  <div class="{{ Metronic::printClasses('subheader-container', false) }} d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
    <div class="d-flex align-items-baseline flex-wrap mr-5">
      <h5 class="text-dark font-weight-bold my-1 mr-5">
        Template
      </h5>
      <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
        <li class="breadcrumb-item">
          <a href="{{ route('dashboard') }}" class="text-muted">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{{ route('olt.template.index') }}" class="text-muted">Olt</a>
        </li>
        <li class="breadcrumb-item">
          <a href="#view" class="text-muted">Template </a>
        </li>
      </ul>
    </div>
  </div>
</div>

@include('inc.error-list')
@include('inc.success-notif')
    <div class="card card-custom">
      <div class="card-header bg-danger flex-wrap border-1 pt-1 pb-0 mb-2" style="min-height: 0;">
        <div class="card-title pt-1 pb-1">
          <h3 class="card-label font-weight-bolder text-white">Template
            <div class="text-muted pt-2 font-size-lg">show Datatable from table Template </div>
          </h3>
        </div>
        <div class="card-toolbar pt-1 pb-0">
          <a  href="{{ route('olt.template.page','new') }}" onclick="show_datas('')" class="btn btn-primary font-weight-bolder" style="background-color: #1e1e2d;border-color: #0c8eff;">
            <span class="svg-icon svg-icon-md">
              <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                  <rect x="0" y="0" width="24" height="24"></rect>
                  <circle fill="#000000" cx="9" cy="15" r="6"></circle>
                  <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3"></path>
                </g>
              </svg>
            </span>Add New
          </a>
        </div>
      </div>
	<div class="card-body pt-1">
		<table class="table table-bordered table-hover w100" cellspacing="0"
			id="datatable" style="width: 1070px !important;"></table>
	</div>
  <div class="card-body py-1">
		<div class="col-lg-12">
			<div class="row justify-content-center py-2 px-2 py-md-10 px-md-0">
				<div class="table-responsive">
						<h3 class="pt-0"><div id="color-picker-1" class="mx-auto">Template Detail</div></h3>
							<table id="datatable_template_detail" class="table dataTable table-bordered table-hover w100" cellspacing="0">
									<thead>
										<tr>
												<th class="text-center text-white dt-body-nowrap">GemPort</th>
												<th class="text-center text-white dt-body-nowrap">Vlan</th>
												<th class="text-center text-white dt-body-nowrap">UserVlan</th>
												<th class="text-center text-white dt-body-nowrap">InnerVlan</th>
												<th class="text-center text-white dt-body-nowrap">TagTransform</th>
												<th class="text-center text-white dt-body-nowrap">TrafficTable</th>
												<th class="text-center text-white dt-body-nowrap">Remark</th>
										</tr>
									</thead>
									<tbody>
									</tbody>
							</table>
					</div>
			</div>
		</div>
	</div>
</div>

@endsection {{-- Styles Section --}} @section('styles')
<link rel="stylesheet"
	href="{{ config('app.url') }}global/vendor/datatables-bootstrap/dataTables.bootstrap.css">
<link rel="stylesheet"
	href="{{ config('app.url') }}global/vendor/datatables-responsive/dataTables.responsive.min.css">
<link rel="stylesheet"
	href="{{ config('app.url') }}plugins/custom/datatables/datatables.bundle.css">
<link rel="stylesheet" href="{{ config('app.url') }}css/inject.css">
@endsection {{-- Scripts Section --}} @section('scripts') @include('inc.confirm-delete-modal')
<script
	src="{{ config('app.url') }}global/vendor/datatables/jquery.dataTables.js"></script>
<script
	src="{{ config('app.url') }}global/vendor/datatables-bootstrap/dataTables.bootstrap.js"></script>
<script
	src="{{ config('app.url') }}global/vendor/datatables-responsive/dataTables.responsive.js"></script>
<script type="text/javascript">
  $("html").keydown(function(e){
    if(e.shiftKey && e.keyCode == 'N'.charCodeAt(0) && !e.altKey){
         show_data('');
     }
  });
  $(document).ready(function() {
    $("#datatable_wrapper").removeClass("dataTables_wrapper form-inline dt-bootstrap no-footer");
    $("#datatable_wrapper").addClass("dataTables_wrapper dt-bootstrap4 no-footer");
  });

  $('[data-switch=true]').bootstrapSwitch();
  $("#TemplateModel").select2();
  $("#TemplateVersion").select2();
  var table = $('#datatable').dataTable({
    pageLength: 5,
    responsive: true,
    searchDelay: 800,
		pagingTypeSince : 'numbers',
    pagingType      : 'full_numbers',
		deferRender: true,
		render: true,
		stateSave: true,
		serverSide: true,
    processing: true,
    searching: true,
		select: true,
		rowId: 'id',
    lengthMenu: [[5, 10, 25, 50, 100, 200], [5, 10, 25, 50, 100, 200]],
    ajax: {
      method: 'POST',
      url : '{{ route('olt.template.data') }}',
      headers: {
        'X-CSRF-TOKEN': '{{ csrf_token() }}'
      }
    },
    columns: [
      {title: "No", data: 'DT_RowIndex', defaultContent: '-', class: 'text-center dt-body-nowrap', orderable: false, searchable: false, autoHide: false},
			{title: "Code", data: 'Code', defaultContent: '-', class: 'text-center dt-body-nowrap', autoHide: false},
			{title: "Name", data: 'Name', defaultContent: '-', class: 'text-center dt-body-nowrap', autoHide: false},
			{title: "VlanDownLink", data: 'VlanDownLink', defaultContent: '-', class: 'text-center dt-body-nowrap', autoHide: false},
			{title: "OntLineProfileId", data: 'OntLineProfileId', defaultContent: '-', class: 'text-center dt-body-nowrap', autoHide: false},
			{title: "OntSrvProfileId", data: 'OntSrvProfileId', defaultContent: '-', class: 'text-center dt-body-nowrap', autoHide: false},
			{title: "NativeVlanEth1", data: 'NativeVlanEth1', defaultContent: '-', class: 'text-center dt-body-nowrap', autoHide: false},
			{title: "NativeVlanEth2", data: 'NativeVlanEth2', defaultContent: '-', class: 'text-center dt-body-nowrap', autoHide: false},
			{title: "NativeVlanEth3", data: 'NativeVlanEth3', defaultContent: '-', class: 'text-center dt-body-nowrap', autoHide: false},
			{title: "NativeVlanEth4", data: 'NativeVlanEth4', defaultContent: '-', class: 'text-center dt-body-nowrap', autoHide: false},
      {title: "VlanAttribut", data: 'VlanAttribut', defaultContent: '-', class: 'text-center dt-body-nowrap', autoHide: false},
      {title: "Remark", data: 'Remark', defaultContent: '-', class: 'text-center dt-body-nowrap', autoHide: false},
      {title: "Actions", data: 'action', orderable: false, responsivePriority: -1},
    ],
    order: [[1, 'asc']],
    bStateSave: true,
    columnDefs: [
      {
        render: function ( data, type, row ) {
						var url = "{{route('olt.template.page', 'prm_code')}}";
						var url_destroy = "{{route('olt.template.destroy', 'prm_code')}}";
						var code = "'"+row.Code+"'";
						var status = "'"+row.ClientStatus+"'";
						var html = ""
        				html+= '<a href="'+url.replaceAll('prm_code',row.Code)+'" class="btn btn-icon btn-light btn-hover-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Edit"><span class="svg-icon svg-icon-md svg-icon-primary"><i class="far flaticon-edit icon-lg"></i></span></a>';
        				html+= '<a data-href="'+url_destroy.replaceAll('prm_code',row.Code)+'" class="btn btn-icon btn-light btn-hover-danger btn-sm" "data-toggle="tooltip" data-placement="top" title="Delete" data-toggle="modal" data-target="#confirm-delete-modal" ><span class="svg-icon svg-icon-md svg-icon-danger"><i class="far flaticon-delete icon-lg"></i></span></a>';

						return html;
        },
        targets: [-1],
        className: 'text-center dt-body-nowrap'
      },
    ],
    initComplete: function() {
      $('.tl-tip').tooltip();
      @if (count($errors) > 0)
      // jQuery("html, body").animate({
      //   scrollTop: $('#add-form').offset().top - 100 // 66 for sticky bar height
      // }, "slow");
      @endif
    }
  });

	$('#datatable tbody').on( 'click', 'tr', function () {
    $("#datatable_template_detail tbody>tr").remove();
        if ($(this).hasClass('selected')) {
            $(this).removeClass('selected');
            $('.Code').html("Data not selected");
        }
        else {
            table.$('tr.selected').removeClass('selected');
            $(this).addClass('selected');
            var id = $(this).find("td:eq(1)").html();
            $("#data-olt").loading("start");
            $.ajax({
                url: "{{ route('olt.template.show-header','')}}/" + id,
                type: "GET",
                headers: {
                  'X-CSRF-TOKEN': '{{ csrf_token() }}'
                },
                success: function (response) {
                  if(response.data["template_detail"]){
                      $("#datatable_template_detail tbody>tr").remove();
                      for (var i in response.data["template_detail"]){
                          var table = document.getElementById("datatable_template_detail").getElementsByTagName('tbody')[0];
                          var row = table.insertRow(-1);
                          row.insertCell(0).innerHTML = '<label class="col-12 text-center">'+response.data["template_detail"][i].GemPort+'</label>';
                          row.insertCell(1).innerHTML = '<label class="col-12 text-center">'+response.data["template_detail"][i].Vlan+'</label>';
                          row.insertCell(2).innerHTML = '<label class="col-12 text-center">'+response.data["template_detail"][i].UserVlan+'</label>';
                          row.insertCell(3).innerHTML = '<label class="col-12 text-center">'+response.data["template_detail"][i].InnerVlan+'</label>';
                          row.insertCell(4).innerHTML = '<label class="col-12 text-center">'+response.data["template_detail"][i].TagTransform+'</label>';
													row.insertCell(5).innerHTML = '<label class="col-12 text-center">'+response.data["template_detail"][i].TrafficTable+'</label>';
                          row.insertCell(6).innerHTML = '<label class="col-12 text-center">'+response.data["template_detail"][i].Remark+'</label>';
                      }
                    }
										$("#data-olt").loading("stop");
                },
                error: function (xhr, status, error) {
                  $("#data-olt").loading("stop");
                  // showDialog.show(xhr.status + " " + status + " " + error, false);
                }
            });
        }
    });


  function refresh_table() {
      $('#datatable').dataTable().ajax.reload();
  }

  function format_date(val) {
      var date_arr = val.split(" ");
      var time = date_arr[1];
      var date_id_arr = date_arr[0].split("-");
      var date_fix = date_id_arr[2] + "-" + date_id_arr[1] + "-" + date_id_arr[0];
      var date_transaction = date_fix + " " + time;
      return date_transaction;
  }
</script>
@endsection